export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const SET_MODAL = "SET_MODAL";
export const REMOVE_MODAL = "REMOVE_MODAL";
export const SET_SPINNER = "SET_SPINNER";
export const REMOVE_SPINNER = "REMOVE_SPINNER";
export const SET_MESSAGE = "SET_MESSAGE";

export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";
export const ADD_NEW_CATEGORY_REQUEST = "ADD_NEW_CATEGORY_REQUEST";
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS";
export const ADD_NEW_CATEGORY_FAIL = "ADD_NEW_CATEGORY_FAIL";

export const APP_IS_ONLINE = "APP_IS_ONLINE"
export const APP_IS_OFFLINE = "APP_IS_OFFLINE"

export const SET_SLIDER = "SET_SLIDER"
export const REMOVE_SLIDER = "REMOVE_SLIDER"
